
# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: ubuntu-latest

variables:
  environmentName: "provision-vm-example-0001"
  token: "lggtba64uhz3copj2a3v5b77rsetpsco2idhbsirjxyz6vxdm7hq"

stages:
- stage: Provision
  jobs:
  - job:
    steps:
      - task: AzureCLI@2
        displayName: 'Create Environment'
        continueOnError: true
        inputs:
          azureSubscription: 'ServiceConnectionForAzureTestPipeline'
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: az group create --name $(environmentName) --location japaneast;
      
      - task: AzureCLI@2
        displayName: 'Create VM'
        continueOnError: true
        inputs:
          azureSubscription: 'ServiceConnectionForAzureTestPipeline'
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            az vm create --name ProvisionedVM --image UbuntuLTS --location japaneast --generate-ssh-keys --resource-group $(environmentName);
    
      # - task: AzureCLI@2
      #   displayName: 'Install web server'
      #   continueOnError: true
      #   inputs:
      #     azureSubscription: 'ServiceConnectionForAzureTestPipeline'
      #     scriptType: pscore
      #     scriptLocation: inlineScript
      #     inlineScript: |
      #       az vm run-command invoke -g $(environmentName) -n ProvisionedVM --command-id RunShellScript --scripts "sudo apt-get update && sudo apt-get install -y nginx"

      # - task: AzureCLI@2
      #   displayName: 'Set web traffic'
      #   continueOnError: true
      #   inputs:
      #     azureSubscription: 'ServiceConnectionForAzureTestPipeline'
      #     scriptType: pscore
      #     scriptLocation: inlineScript
      #     inlineScript: |
      #       az vm open-port --port 80 --resource-group $(environmentName) --name ProvisionedVM;
          
      - task: AzureCLI@2
        displayName: 'Register VM'
        inputs:
          azureSubscription: 'ServiceConnectionForAzureTestPipeline'
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            az vm extension set `
              --publisher Microsoft.Azure.Extensions `
              --version 2.0 `
              --name CustomScript `
              --vm-name ProvisionedVM `
              --resource-group $(environmentName) `
              --settings "{`\`"fileUris`\`": [`\`"https://raw.githubusercontent.com/blue0316/azure-pipeline-puppeteer/main/register-server-in-environment.sh`\`"],`\`"commandToExecute`\`": `\`"./register-server-in-environment.sh`\`"}";
      - task: AzureCLI@2
        displayName: 'Install web server'
        continueOnError: true
        inputs:
          azureSubscription: 'ServiceConnectionForAzureTestPipeline'
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            az vm run-command invoke -g $(environmentName) -n ProvisionedVM --command-id RunShellScript --scripts "mkdir azagent;cd azagent;curl -fkSL -o vstsagent.tar.gz https://vstsagentpackage.azureedge.net/agent/2.211.1/vsts-agent-linux-x64-2.211.1.tar.gz;tar -zxvf vstsagent.tar.gz; if [ -x "$(command -v systemctl)" ]; then ./config.sh --environment --environmentname "provision-vm-example-0001" --acceptteeeula --agent $HOSTNAME --url https://dev.azure.com/shanthan0479/ --work _work --projectname 'AzureTestProject' --auth PAT --token cntfjfs77vlf52g5xp6744tdtj5m5dd3ot4yg34qrsbcqlpdzw2q --runasservice; sudo ./svc.sh install; sudo ./svc.sh start; else ./config.sh --environment --environmentname "provision-vm-example-0001" --acceptteeeula --agent $HOSTNAME --url https://dev.azure.com/shanthan0479/ --work _work --projectname 'AzureTestProject' --auth PAT --token cntfjfs77vlf52g5xp6744tdtj5m5dd3ot4yg34qrsbcqlpdzw2q; ./run.sh; fi"

      

- stage: Test
  dependsOn: Provision
  condition: succeeded()
  displayName: Test Stage
  jobs:
  - deployment: TestCustomTask
    displayName: Deploy Web App
    environment:
      name: provision-vm-example-0001
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '16.x'
            displayName: 'Install Node.js'
          - script: |
              git clone https://github.com/blue0316/puppeteer-test-project.git
            displayName: 'git clone'
            continueOnError: true
          - task: Npm@1
            displayName: 'install node packages'
            inputs:
              command: 'install'
              workingDir: 'puppeteer-test-project'
            continueOnError: true
          - task: Npm@1
            displayName: 'start test project'
            inputs:
              command: ci
              workingDir: 'puppeteer-test-project'
            continueOnError: true

- stage: CleanUp
  jobs:
  - job:
    steps:
      - task: AzureCLI@2
        displayName: 'Destroy Environment'
        continueOnError: true
        inputs:
          azureSubscription: 'ServiceConnectionForAzureTestPipeline'
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: az group delete --name $(environmentName) --no-wait --yes;